language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=4.5    WP_MULTISITE=0
  - WP_VERSION=4.4    WP_MULTISITE=0
  - WP_VERSION=4.3    WP_MULTISITE=0
  - WP_VERSION=4.2    WP_MULTISITE=0
  - WP_VERSION=4.1    WP_MULTISITE=0
  - WP_VERSION=4.0    WP_MULTISITE=0

before_install:
  - pip install --user codecov

before_script:
  - composer self-update
  - composer -q install

script: ./bin/test-ci.sh

after_success:
  - cp var/phpunit/coverage.xml .
  - codecov